/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MenuSocial {
    }
}
declare global {
    interface HTMLMenuSocialElement extends Components.MenuSocial, HTMLStencilElement {
    }
    var HTMLMenuSocialElement: {
        prototype: HTMLMenuSocialElement;
        new (): HTMLMenuSocialElement;
    };
    interface HTMLElementTagNameMap {
        "menu-social": HTMLMenuSocialElement;
    }
}
declare namespace LocalJSX {
    interface MenuSocial {
    }
    interface IntrinsicElements {
        "menu-social": MenuSocial;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "menu-social": LocalJSX.MenuSocial & JSXBase.HTMLAttributes<HTMLMenuSocialElement>;
        }
    }
}
